version: 2.1

jobs:
  eloqua-wrapper:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
orbs:
  ruby: circleci/ruby@1.2.0

workflows:
  eloqua-wrapper-workflow:
    jobs:
      - eloqua-wrapper
