version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  eloqua-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: '2.3'
      - ruby/install-deps:
          with-cache: false
          bundler-version: '1.17'
          path: /
      - ruby/rspec-test
workflows:
  eloqua-workflow:
    jobs:
      - eloqua-job