version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: '2.6.3' 
      - ruby/rspec-test:
          label: rspec-checks 

workflows:
  example-workflow:
    jobs:
      - example-job