orbs:
  ruby: circleci/ruby@1.2.0
version: 2.1
jobs:
  test-build:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
workflows:
  eloqua-build:
    jobs:
      - test-build
