version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:2.6.3'
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
orbs:
  ruby: circleci/ruby@1.2.0

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
