version: 2.1

jobs:
  eloqua-wrapper:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install:
          version: '2.6.3'
      - ruby/install-deps
      - ruby/rspec-test
orbs:
  ruby: circleci/ruby@1.2.0

workflows:
  eloqua-wrapper-workflow:
    jobs:
      - eloqua-wrapper
