version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  eloqua-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: '2.6.3'
      - ruby/install-deps
      - ruby/rspec-test
workflows:
  eloqua-workflow:
    jobs:
      - eloqua-job