version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:2.6.3'
      - environment:
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-demo-ruby
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-demo-ruby
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
orbs:
  ruby: circleci/ruby@1.2.0

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
