jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: 'cimg/ruby:2.6.3'
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: '1.17'
      - ruby/rspec-test
orbs:
  ruby: circleci/ruby@1.2.0
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
